---
title: "Home page: returning moves user from previous position"
labels: ["bug"]
assignees: ["NEVARLeVrai"]
body: |
  **Android Version**: Other
  **App Version**: nightly
  
  **Required Actions**:
  - true
  - true
  - true
  
  **Bug Trigger**: Leave home page, return: app moves you to a different spot than before.
  
  **Expectation**: Returning to home should restore user's previous position in UI.
  
  **Log**: 
  
  **Other Android Version**: 
  
  **Video**: 
