---
name: Bug Report
about: Create a report to notify the team of a bug.
title: 'Sleep timer uses outdated UI; needs new Settings UI refactor'
labels: [bug]
assignees: [NEVARLeVrai]
---

### Bug Details

**Android Version:** Other  
**App Version:** nightly  

**Required Actions:**  
- [x] true  
- [x] true  
- [x] true  

**Bug Trigger:**  
Open sleep timer function. Observe it uses previous UI design; lacks modern Settings UI elements. Needs refactor.  

**Expectation:**  
Sleep timer should present modern, consistent Settings UI, matching other settings screens.  

**Log:**  

**Other Android Version:**  

**Video:**  
