---
title: "Listen On uses old UI; migrate to new Settings UI"
labels: ["bug"]
assignees: ["NEVARLeVrai"]
---

## Form Values
- **android-version:** Other
- **app-version:** nightly
- **required-actions:** true, true, true
- **bug-trigger:** Open 'Listen On'. UI displayed is not up-to-date. Needs migration to new Settings UI.
- **expectation:** Listen On should use new Settings UI for improved look and consistency.
- **log:** 
- **other-android-version:** 
- **video:** 
